### ISSUE TITLE
[CSS] height 자동으로 설정하기 

### ISSUE THREAD

**Issue by moonheekim0118** [moonheekim0118/tips#5]
- 내부에 들어간 컨텐츠가 overflow 되지 않도록 하고 싶을 때, (overflow 되는 경우 알아서 스크롤 생기도록 )
- min height 설정해서 height이 긴 창에서도 창의 길이가 남지 않도록 

```css
  html {
    height: auto;
    min-height: 100%;
    overflow-x: hidden;
    overflow-y: auto;
  }
```
